version: '3.1'

services: 
  mongo-spring:
    image: mongo
    container_name: mongo-container
    networks:
      - springboot-compose-network
    ports:
      - 27017:27017
    restart: always
    volumes: 
      - ./data:/dataSpring/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongoadmin
 
  springboot:
    links:
      - mongo-spring
    image: spring-docker-example:0.0.3-SNAPSHOT
    container_name: springboot-container
    depends_on:
      - mongo-spring
    networks:
      - springboot-compose-network
    ports:
      - 8080:8080
    restart: always
    volumes: 
      - ./data:/dataSpring/db

networks:
  springboot-compose-network:
    driver: bridge